#!/bin/sh
# Auto-generated by archdots. Do not edit by hand — re-run `archdots export`.
#
# Standalone installer: works on any Arch box; does NOT require archdots.

set -eu

REPO="$(cd "$(dirname "$0")" && pwd)"
DOTFILES="$REPO/dotfiles"
STAMP="$(date +%Y%m%d-%H%M%S)"

echo "==> Installing dependencies"
{IF has_pacman}sudo pacman -S --needed --noconfirm {pacman_deps_str}
{ENDIF}{IF has_aur}echo "==> AUR dependencies — install manually with your AUR helper:"
echo "    {aur_deps_str}"
{ENDIF}
echo "==> Linking files (existing targets backed up with .bak.$STAMP suffix)"
find "$DOTFILES" -type f | while read -r src; do
    rel="${{src#$DOTFILES/}"
    tgt="$HOME/$rel"
    mkdir -p "$(dirname "$tgt")"
    if [ -e "$tgt" ] || [ -L "$tgt" ]; then
        mv "$tgt" "$tgt.bak.$STAMP"
    fi
    ln -s "$src" "$tgt"
done

echo "==> Done. For atomic apply / rollback / dependency checks, install archdots:"
echo "    https://github.com/njuante/archdots"
