//! Implementation of `archdots apply`.

use anyhow::{bail, Context, Result};
use archdots_core::{
    journal::{Journal, LinkOutcome},
    linker::{ApplyOptions, LinkDisposition, LinkSpec, Linker},
    profile::{Profile, ResolveCtx},
    snapshot::SnapshotManager,
};

use crate::{cmd, xdg};

pub fn run(profile_name: &str, dry_run: bool, force: bool, yes: bool) -> Result<()> {
    let home = xdg::home_dir()?;
    let data_home = xdg::data_home()?;
    let state_home = xdg::state_home()?;

    let profile_path = xdg::profiles_dir()?.join(format!("{profile_name}.toml"));
    if !profile_path.exists() {
        bail!(
            "profile '{}' not found at {}",
            profile_name,
            profile_path.display()
        );
    }

    let profile = Profile::load_from_file(&profile_path)
        .with_context(|| format!("failed to load profile '{profile_name}'"))?;

    // source paths in profiles generated by `init` are relative to $HOME
    let ctx = ResolveCtx::with_home(&home);
    let specs: Vec<LinkSpec> = profile
        .resolved_entries(&home, &ctx)
        .map(|r| {
            let (_entry, src, tgt) = r?;
            Ok(LinkSpec {
                source: src,
                target: tgt,
            })
        })
        .collect::<std::result::Result<_, archdots_core::error::ProfileError>>()
        .context("failed to resolve profile entries")?;

    let snapshots = SnapshotManager::open(&data_home)?;
    let journal = Journal::open(&state_home)?;
    let linker = Linker::new(&snapshots, &journal);

    let plan = linker.plan(profile_name, &specs, &home)?;

    print_plan_table(&plan.items);

    if dry_run {
        println!(
            "(dry-run) plan shows {} link(s); no changes made.",
            plan.items.len()
        );
        return Ok(());
    }

    let conflict_items: Vec<_> = plan
        .items
        .iter()
        .filter(|item| matches!(item.disposition, LinkDisposition::Conflict(_)))
        .collect();

    if !conflict_items.is_empty() && !force {
        eprintln!("{} conflict(s) detected:", conflict_items.len());
        for item in &conflict_items {
            if let LinkDisposition::Conflict(r) = item.disposition {
                eprintln!("  {} — {r:?}", item.spec.target.display());
            }
        }
        eprintln!("Use --force to override, or fix the conflicts first.");
        std::process::exit(2);
    }

    if !yes {
        let active = plan
            .items
            .iter()
            .filter(|item| {
                !matches!(
                    item.disposition,
                    LinkDisposition::AlreadyOwned | LinkDisposition::Conflict(_)
                )
            })
            .count();
        if !cmd::confirm(&format!("Apply {active} link(s)?"))? {
            println!("Aborted.");
            return Ok(());
        }
    }

    let opts = ApplyOptions {
        dry_run: false,
        force,
        home,
        state_home,
    };
    let report = linker.apply(plan, opts)?;

    let n_linked = report
        .applied
        .iter()
        .filter(|r| matches!(r.outcome, LinkOutcome::Linked))
        .count();
    let n_skipped = report
        .applied
        .iter()
        .filter(|r| matches!(r.outcome, LinkOutcome::Skipped))
        .count();
    let n_failed = report
        .applied
        .iter()
        .filter(|r| matches!(r.outcome, LinkOutcome::Failed(_)))
        .count();

    println!("Result: {n_linked} linked, {n_skipped} skipped, {n_failed} failed");
    println!("Journal ID:  {}", report.journal_id);
    if let Some(snap_id) = &report.snapshot_id {
        println!("Snapshot ID: {snap_id}");
    }

    if report.rolled_back || n_failed > 0 {
        std::process::exit(1);
    }

    Ok(())
}

fn print_plan_table(items: &[archdots_core::linker::PlannedLink]) {
    const TGT_W: usize = 48;
    const DISP_W: usize = 22;
    println!(
        "{:<TGT_W$}  {:<DISP_W$}  prior_state",
        "target", "disposition"
    );
    println!("{}", "─".repeat(TGT_W + DISP_W + 16));
    for item in items {
        let tgt = item.spec.target.display().to_string();
        let tgt_disp = if tgt.len() > TGT_W {
            format!("…{}", &tgt[tgt.len() - TGT_W + 1..])
        } else {
            tgt
        };
        let disp_str = disposition_label(&item.disposition);
        let prior_str = prior_label(&item.prior_state);
        println!("{tgt_disp:<TGT_W$}  {disp_str:<DISP_W$}  {prior_str}");
    }
    println!();
}

fn disposition_label(d: &archdots_core::linker::LinkDisposition) -> &'static str {
    match d {
        archdots_core::linker::LinkDisposition::Create => "create",
        archdots_core::linker::LinkDisposition::ReplaceFile => "replace-file",
        archdots_core::linker::LinkDisposition::ReplaceSymlink { .. } => "replace-symlink",
        archdots_core::linker::LinkDisposition::AlreadyOwned => "already-owned",
        archdots_core::linker::LinkDisposition::Conflict(r) => conflict_label(*r),
        archdots_core::linker::LinkDisposition::SkipDir => "skip-dir",
        _ => "unknown",
    }
}

fn conflict_label(r: archdots_core::linker::ConflictReason) -> &'static str {
    match r {
        archdots_core::linker::ConflictReason::ParentMissing => "conflict:parent-missing",
        archdots_core::linker::ConflictReason::PermissionDenied => "conflict:permission-denied",
        archdots_core::linker::ConflictReason::OutsideHome => "conflict:outside-home",
        archdots_core::linker::ConflictReason::SourceMissing => "conflict:source-missing",
        archdots_core::linker::ConflictReason::TargetIsDirectory => "conflict:target-is-dir",
        _ => "conflict:unknown",
    }
}

fn prior_label(p: &archdots_core::journal::PriorState) -> &'static str {
    match p {
        archdots_core::journal::PriorState::Absent => "absent",
        archdots_core::journal::PriorState::File => "file",
        archdots_core::journal::PriorState::Dir => "dir",
        archdots_core::journal::PriorState::Symlink { .. } => "symlink",
        _ => "unknown",
    }
}
