//! Implementation of `archdots init`.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use archdots_core::detector::DetectedDotfile;
use archdots_core::detector::Detector;
use archdots_core::profile::{
    Dependencies, FileEntry, Hooks, LinkMode, Profile, ProfileMeta, CURRENT_SCHEMA_VERSION,
};

use crate::xdg;

/// Run `archdots init`.
///
/// Scans `$HOME` for known dotfiles, builds a profile descriptor from the
/// hits, and writes it to `output` (or the default XDG path) without touching
/// any existing file outside the profile directory.
///
/// Fails with an error if the target file already exists and `force` is false.
pub fn run(name: &str, output: Option<PathBuf>, force: bool) -> Result<()> {
    let home = xdg::home_dir()?;

    let out_path = match output {
        Some(p) => p,
        None => xdg::profiles_dir()?.join(format!("{name}.toml")),
    };

    if out_path.exists() && !force {
        anyhow::bail!(
            "profile '{}' already exists at {}. Use --force to overwrite.",
            name,
            out_path.display()
        );
    }

    tracing::debug!(home = %home.display(), output = %out_path.display(), "scanning");

    let detector = Detector::new(&home).context("failed to initialise dotfile detector")?;
    let detected = detector.scan();
    let existing: Vec<DetectedDotfile> = detected.into_iter().filter(|d| d.exists).collect();

    tracing::debug!(found = existing.len(), "scan complete");

    let files = build_file_entries(&existing, &home);
    let file_count = files.len();

    let profile = Profile {
        schema_version: CURRENT_SCHEMA_VERSION,
        profile: ProfileMeta {
            name: name.to_string(),
            description: Some(String::from("Generated by archdots init")),
            author: None,
            created_at: None,
            tags: Vec::new(),
        },
        wm: None,
        files,
        dependencies: Dependencies::default(),
        hooks: Hooks::default(),
    };

    profile
        .validate()
        .with_context(|| format!("generated profile '{name}' is invalid"))?;

    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("cannot create directory {}", parent.display()))?;
    }

    profile
        .save_to_file(&out_path)
        .with_context(|| format!("cannot write profile to {}", out_path.display()))?;

    println!("Profile '{}' saved to {}", name, out_path.display());
    println!("{file_count} dotfile(s) detected.");

    Ok(())
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// Build a unique, sanitised id from an app name and the file's stem.
fn make_id(app_name: &str, rel_path: &Path) -> String {
    let stem = rel_path
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("file")
        .trim_start_matches('.');

    let raw = format!("{app_name}-{stem}").to_lowercase();
    let sanitised: String = raw
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    sanitised.trim_matches('-').to_string()
}

/// Convert detected dotfiles into [`FileEntry`] values for a generated profile.
///
/// * `source` — relative path from `$HOME` (mirrors the XDG tree inside the
///   profile directory).
/// * `target` — the same path expressed as `~/<rel>` so `apply` can expand it.
fn build_file_entries(detected: &[DetectedDotfile], home: &Path) -> Vec<FileEntry> {
    let mut entries = Vec::new();
    let mut id_counts: HashMap<String, usize> = HashMap::new();

    for d in detected {
        let Ok(rel) = d.path.strip_prefix(home) else {
            tracing::warn!(
                path = %d.path.display(),
                "detected path is not under $HOME — skipping"
            );
            continue;
        };

        let base_id = make_id(&d.name, rel);
        let count = id_counts.entry(base_id.clone()).or_insert(0);
        *count += 1;
        let id = if *count == 1 {
            base_id
        } else {
            format!("{base_id}-{count}")
        };

        entries.push(FileEntry {
            id,
            source: rel.to_path_buf(),
            target: format!("~/{}", rel.display()),
            mode: LinkMode::Symlink,
            exec: false,
            required: true,
        });
    }

    entries
}

// ── unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::make_id;

    #[test]
    fn make_id_dotfile_in_home() {
        let id = make_id("zsh", Path::new(".zshrc"));
        assert_eq!(id, "zsh-zshrc");
    }

    #[test]
    fn make_id_xdg_path() {
        let id = make_id("bspwm", Path::new(".config/bspwm/bspwmrc"));
        assert_eq!(id, "bspwm-bspwmrc");
    }

    #[test]
    fn make_id_uppercase_lowercased() {
        let id = make_id("urxvt", Path::new(".Xresources"));
        assert_eq!(id, "urxvt-xresources");
    }

    #[test]
    fn make_id_replaces_dots_with_hyphens() {
        let id = make_id("kitty", Path::new(".config/kitty/kitty.conf"));
        assert_eq!(id, "kitty-kitty-conf");
    }

    #[test]
    fn make_id_no_leading_trailing_hyphens() {
        let id = make_id("x", Path::new("file"));
        assert!(!id.starts_with('-'));
        assert!(!id.ends_with('-'));
    }
}
